lista_contatos=[] # O programa inicia criando uma lista vazia chamada "lista_contatos", que será utilizada para armazenar os contatos do usuário. 

while True: # O programa entra em um loop infinito utilizando a estrutura while True, o que significa que o programa continuará executando até que seja explicitamente interrompido por um break.
    print("-"*5, "CONTATOS", "-"*5) # O programa exibe um título "CONTATOS" cercado por uma linha de caracteres "-" para destacar a seção de contatos.
    print("1 - Adicionar novo contato") # O programa exibe a opção "1 - Adicionar novo contato" informando ao usuário que ele pode escolher essa opção.
    print("2 - Exibir lista de contatos") # O programa exibe a opção "2 - Exibir lista de contatos" informando ao usuário que ele pode escolher essa opção.
    print("3 - Excluir contato") # O programa exibe a opção "3 - Excluir contato" informando ao usuário que ele pode escolher essa opção.
    print("0 - Sair") # O programa exibe a opção "0 - Sair" informando ao usuário que ele pode escolher essa opção para encerrar o programa.

    opcao= input("Digite a opção desejada:") # O programa solicita que o usuário digite a opção desejada e armazena a entrada na variável "opcao". A função input() é utilizada para capturar a entrada do usuário como uma string, permitindo que o programa processe a escolha do usuário.
    if opcao=="0": # O programa verifica se a opção digitada pelo usuário é "0", o que indica que o usuário deseja sair do programa. Se a condição for verdadeira, o programa executa o código dentro do bloco if.
        print("Fim do programa!") # Se a condição if for verdadeira, o programa exibe a mensagem "Fim do programa!" para informar ao usuário que o programa está sendo encerrado.
        break # O comando break é utilizado para sair do loop while, encerrando a execução do programa.

    if opcao in ["1","2","3"]: # O programa verifica se a opção digitada pelo usuário é uma das opções válidas ("1", "2" ou "3"). Se a condição for verdadeira, o programa executa o código dentro do bloco if.
        match int(opcao): # O programa utiliza a estrutura match-case para comparar a opção digitada pelo usuário (convertida para um número inteiro) com os casos definidos. A função int() é utilizada para converter a entrada do usuário em um número inteiro.
            case 1: # Se a opção digitada pelo usuário for "1", o programa executa o código dentro do bloco case 1.
                contato= { # O programa cria um dicionário chamado "contato" para armazenar as informações do contato a ser adicionado. O dicionário é criado utilizando chaves e valores, onde as chaves são "nome", "telefone" e "email", e os valores são obtidos a partir da entrada do usuário.
                "nome" : input("Digite o nome: "), # O programa solicita que o usuário digite o nome do contato e armazena a entrada como o valor associado à chave "nome" no dicionário "contato". A função input() é utilizada para capturar a entrada do usuário como uma string, permitindo que o programa processe o nome do contato.
                "telefone" : input("Digite o telefone: "), # O programa solicita que o usuário digite o telefone do contato e armazena a entrada como o valor associado à chave "telefone" no dicionário "contato". A função input() é utilizada para capturar a entrada do usuário como uma string, permitindo que o programa processe o telefone do contato.
                "email" : input("Digite o e-mail: ") # O programa solicita que o usuário digite o e-mail do contato e armazena a entrada como o valor associado à chave "email" no dicionário "contato". A função input() é utilizada para capturar a entrada do usuário como uma string, permitindo que o programa processe o e-mail do contato.
                } # O dicionário "contato" é criado com as informações fornecidas pelo usuário, representando um contato completo com nome, telefone e e-mail.
                lista_contatos.append(contato) # O programa adiciona o dicionário "contato" à lista "lista_contatos" utilizando o método append(). O método append() é utilizado para adicionar um elemento ao final da lista, permitindo que o programa mantenha um registro dos contatos adicionados à lista de contatos.
                print(f"{contato['nome']} adicionado a lista") # O programa exibe uma mensagem confirmando que o contato foi adicionado à lista de contatos, utilizando f-strings para formatar a saída e incluir o nome do contato adicionado.
            case 2: # Se a opção digitada pelo usuário for "2", o programa executa o código dentro do bloco case 2.
                if len(lista_contatos)==0: # O programa verifica se a lista de contatos está vazia utilizando a função len() para obter o número de elementos na lista. Se o resultado for igual a 0, significa que a lista está vazia, e o programa executa o código dentro do bloco if.
                    print("Lista de contatos vazia.") # Se a condição if for verdadeira, o programa exibe a mensagem "Lista de contatos vazia." para informar ao usuário que não há contatos na lista de contatos.
                else: # Se a condição if for falsa, ou seja, se a lista de contatos não estiver vazia, o programa executa o código dentro do bloco else.
                    print("--- MEUS CONTATOS ---") # O programa exibe o título "--- MEUS CONTATOS ---" para indicar que a próxima seção exibirá os contatos armazenados na lista de contatos.
                    for i, item in enumerate(lista_contatos, 1): # O programa utiliza um loop for para iterar sobre os contatos da lista de contatos, utilizando a função enumerate() para obter tanto o índice (i) quanto o valor do contato (item). O segundo argumento da função enumerate() é 1, o que significa que a contagem dos índices começará em 1 em vez de 0, proporcionando a enumeração dos contatos armazenados.
                        print(f"{i}. Nome: {item['nome']}") # O programa exibe o nome de cada contato em um formato específico. A expressão f"{i}. Nome: {item['nome']}" utiliza f-strings para formatar a saída, exibindo o índice do contato (i) seguido pelo nome do contato (item['nome']).
                        print(f"   Telefone: {item['telefone']}") # O programa exibe o telefone de cada contato em um formato específico. A expressão f"   Telefone: {item['telefone']}" utiliza f-strings para formatar a saída, exibindo o telefone do contato (item['telefone']) com uma indentação para melhor visualização.
                        print(f"   E-mail: {item['email']}") # O programa exibe o e-mail de cada contato em um formato específico. A expressão f"   E-mail: {item['email']}" utiliza f-strings para formatar a saída, exibindo o e-mail do contato (item['email']) com uma indentação para melhor visualização.
                    print("-"*25) # O programa exibe uma linha de 25 caracteres "-" para separar visualmente a lista de contatos exibida.
            case 3: # Se a opção digitada pelo usuário for "3", o programa executa o código dentro do bloco case 3.
                excluir=input("Digite o nome do contato a ser excluído: ") # O programa solicita que o usuário digite o nome do contato a ser excluído da lista de contatos e armazena a entrada na variável "excluir". A função input() é utilizada para capturar a entrada do usuário como uma string, permitindo que o programa processe o nome do contato a ser excluído.
                encontrado= False # O programa inicia uma variável "encontrado" com o valor False, que será utilizada para indicar se o contato a ser excluído foi encontrado na lista de contatos. Essa variável é importante para controlar o fluxo do programa e fornecer feedback adequado ao usuário sobre o resultado da operação de exclusão.
                for item in lista_contatos: # O programa utiliza um loop for para iterar sobre os contatos da lista de contatos, representados pela variável "item". Durante a iteração, o programa verifica se o nome do contato a ser excluído (excluir) corresponde ao nome do contato atual (item['nome']) utilizando uma comparação que ignora espaços em branco e diferenças de maiúsculas e minúsculas.
                    if excluir.strip().lower() == item['nome'].strip().lower(): # O programa compara o nome do contato a ser excluído (excluir) com o nome do contato atual (item['nome']) utilizando os métodos strip() e lower() para remover espaços em branco e converter ambos os nomes para minúsculas, garantindo que a comparação seja feita de forma consistente, independentemente de diferenças de formatação ou capitalização.
                        lista_contatos.remove(item) # Se a condição if for verdadeira, ou seja, se o nome do contato a ser excluído corresponder ao nome do contato atual, o programa remove o contato da lista de contatos utilizando o método remove(). O método remove() é utilizado para remover a primeira ocorrência de um elemento na lista, permitindo que o programa exclua o contato correspondente.
                        print(f"{excluir} excluído da lista!") # O programa exibe uma mensagem confirmando que o contato foi excluído da lista de contatos, utilizando f-strings para formatar a saída e incluir o nome do contato excluído.
                        encontrado= True # O programa define a variável "encontrado" como True para indicar que o contato a ser excluído foi encontrado na lista de contatos.
                        break   # O comando break é utilizado para sair do loop for, encerrando a iteração sobre os contatos da lista de contatos, uma vez que o contato a ser excluído foi encontrado e removido da lista.
                if not encontrado: # O programa verifica se a variável "encontrado" é False utilizando a expressão not encontrado. Se a condição for verdadeira, significa que o contato a ser excluído não foi encontrado na lista de contatos, e o programa executa o código dentro do bloco if.
                    print(f"{excluir} não encontrado na lista") # O programa exibe uma mensagem informando que o contato a ser excluído não foi encontrado na lista de contatos, utilizando f-strings para formatar a saída e incluir o nome do contato que não foi encontrado.

    else: # Se a condição if for falsa, ou seja, se a opção digitada pelo usuário não for "0", "1", "2" ou "3", o programa executa o código dentro do bloco else.
        print("Digite apenas as opções válidas") # O programa exibe a mensagem "Digite apenas as opções válidas" para informar ao usuário que a opção digitada não é válida e que ele deve digitar uma opção válida para continuar utilizando o programa.


